### ISSUE TITLE
The green lines in cooja 

### ISSUE THREAD

**Issue by iliar** [mbaddeley/usdn#5]
Hi,
Do the green lines specify the control flow and blue lines the data flow?
The problem is that the green lines are always pointed to node 1. Can't we have multiple controllers? Can the controller be any node other than node 1?

**Comment by mbaddeley** [comment]
The green lines are purely indicative that the node has connected to the SDN controller. 

The blue lines are default in the Cooja simulate and show ALL transmissions (RPL, uSDN, Application Data, ... )

uSDN (in theory) supports the concept of multiple controllers, and it is something that I wanted to do, HOWEVER (and this is a very big however) there is currently nothing in uSDN governing this connection process, although there is code that allows it. This would need to be your own project :)

There are two ways you could go about this...

1) Use multiple RPL DAGs, where each root node is a controller.
2) Have multiple controllers in a single DAG, and implement a connect/disconnect process where nodes try to connect to their closest controller (this would be a lot of work and is probably not going to be that successful due to the additional overhead this will force on the RPL control plane)
3) Implement some sort of hierarchical controller system (this would again be a lot of work, but if you read the relevant literature on SDN for constrained networks then this is probably the way things are going).

... however all these options also introduce another problem -> How do the controllers speak to one another (SDN East/West interfaces)?

Essentially the main issue is overhead. With a multiple controller scenario what you are introducing the East/West control interface and this introduces additional signalling messages, which is what uSDN tries to avoid.

If you do go ahead with this then let me know, it's an interesting problem and I'd be happy to correspond via email :)

Good luck!

**Comment by mbaddeley** [comment]
Oh, also, to set the controller to another node, you can do this in sdn-conf.h:

`Line 90: #define SDN_CONF_CONTROLLER_IP(addr)        uip_ip6addr(addr, 0xaaaa, 0, 0, 0, 0, 0, 0, 1);`

However you need to make sure that this new node is also the RPL dag root (sdn-controller.c node), as RPL is used for the control plane topology.
